"""empty message

Revision ID: 560491dcc12d
Revises: 9a464101e71b
Create Date: 2018-11-26 20:56:00.361299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560491dcc12d'
down_revision = '9a464101e71b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
