"""empty message

Revision ID: 7ae43e072b04
Revises: 6a95cb77759f
Create Date: 2018-11-26 14:45:42.637427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ae43e072b04'
down_revision = '6a95cb77759f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.drop_column('users', 'member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('member', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'member_since')
    # ### end Alembic commands ###
