"""empty message

Revision ID: 861192f68f75
Revises: 032b9afaec49
Create Date: 2018-11-28 04:22:50.501287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861192f68f75'
down_revision = '032b9afaec49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'body_html')
    # ### end Alembic commands ###
